name: Remove All Labels

on:
  pull_request:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
